version: '3'

services:
  web:
    image: httpd
    environment:
      - ENVIRONMENT=dev
    networks:
      - dev_network
      - prod_network
      - lab_network

  db:
    image: mysql
    environment:
      - ENVIRONMENT=dev
      - MYSQL_ROOT_PASSWORD=root_passwd
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_passwd
    networks:
      - dev_network
      - prod_network
      - lab_network
    

networks:
  dev_network:
    driver: bridge

  prod_network:
    driver: bridge

  lab_network:
    driver: bridge
